
project_id = "your-project-id"

[functions.lucie-chat]
verify_jwt = true

[functions.ai-companion-chat]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true

[functions.lucie-visual-response]
verify_jwt = true
