
# This file is used to configure the Supabase project

project_id = "haffqtqpbnaviefewfmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[api.cors]
enabled = true
optional_methods = ["OPTIONS", "HEAD", "PATCH", "PUT", "DELETE"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[inbucket]
enabled = true
port = 54324

[studio]
enabled = true
port = 54323

[functions]
[functions.process-companion-payment]
verify_jwt = true
