
project_id = "haffqtqpbnaviefewfmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.generate-nsfw-image]
verify_jwt = true

[functions.generate-escort-image]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.nsfw-image-generation]
verify_jwt = true
