
project_id = "haffqtqpbnaviefewfmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Enable realtime functionality for our key tables
[[realtime.tables]]
name = "bookings"
schema = "public"

[[realtime.tables]]
name = "verification_requests"
schema = "public"

[[realtime.tables]]
name = "notifications"
schema = "public"

[[realtime.tables]]
name = "content_purchases"
schema = "public"

[[realtime.tables]]
name = "messages"
schema = "public"

[[realtime.tables]]
name = "content_monetization"
schema = "public"

[functions.process-content-purchase]
verify_jwt = true
