
project_id = "haffqtqpbnaviefewfmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[[functions]]
verify_jwt = true
name = "iota-service"
