
export const AppPaths = {
  HOME: '/',
  ESCORT_SEARCH: '/escorts',
  ESCORT_DETAIL: '/escort/:id',
  CREATORS: '/creators',
  CREATOR_DETAIL: '/creator/:id',
  AI_COMPANION: '/ai-companions',
  AI_COMPANION_DETAIL: '/ai-companion/:id',
  MESSAGES: '/messages',
  WALLET: '/wallet',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  VERIFICATION: '/verification',
  PULSE_BOOST: '/pulse-boost',
  LUCIE: '/lucie',
  OXUM: '/oxum',
  HERMES: '/hermes',
  LOGIN: '/login',
  REGISTER: '/register',
  BRAIN_HUB: '/brain-hub',
  NEURAL_ANALYTICS: '/neural-analytics',
  METAVERSE: '/metaverse',
}
