
export enum AppPaths {
  HOME = '/',
  AUTH = '/auth',
  DASHBOARD = '/dashboard',
  PROFILE = '/profile',
  MESSAGES = '/messages',
  WALLET = '/wallet',
  FAVORITES = '/favorites',
  ESCORTS = '/escorts',
  ESCORT_DETAIL = '/escorts/:id',
  CREATORS = '/creators',
  CREATOR_DETAIL = '/creators/:id',
  LIVECAMS = '/livecams',
  LIVECAM_DETAIL = '/livecams/:id',
  SETTINGS = '/settings',
  ADMIN = '/admin',
  SEO = '/seo-dashboard',
  SAFETY = '/safety',
  NEURAL_MONITOR = '/neural-monitor',
  NEURAL_ANALYTICS = '/neural-analytics',
  MEDIA_GENERATION = '/media-generation',
  NSFW_GENERATOR = '/nsfw-generator',
  LUCIE = '/lucie',
  BOOKING = '/book',
  VERIFICATION = '/verification'
}
